### ISSUE TITLE
patch operation with/without filter grouping

### ISSUE THREAD

**Issue by chihoyeung** [PowerDMS/Owin.Scim#10]
This is low priority and not sure if it is a problem or not.

On a patch remove operation with path:"emails[type eq "work"]" it removes the matching email complex attribute.

On a patch remove operation with path:"emails.type eq "work" " it ALSO removes the matching email complex attribute. I was expecting it to clear the type sub-attribute, but the spec is not clear on how to handle this scenario.

**Comment by Cephei** [comment]
Interesting ... I interpreted the spec as both of those are equal paths.  In fact I intentionally normalize path/filters by injecting groupings `[]` where `.` are used to designate a sub-attribute filter vs a sub-attribute target property.

In it's current state, the path normalizer will take `emails.type eq "work"` and turn it into `emails[type eq "work"]` before being used by the lexer/parser to create an expression-tree predicate.

It's my opinion that if you want to modify just the type sub-attribute you have to append it after the filter.
Thus, to filter and modify email.type: `emails[type eq "work"].type`

**Comment by Cephei** [comment]
https://www.ietf.org/mail-archive/web/scim/current/msg02589.html
