### ISSUE TITLE
Can we change signature for IUserRepository.DeleteUser?

### ISSUE THREAD

**Issue by chihoyeung** [PowerDMS/Owin.Scim#29]
Currently, the signature for this methods is:

`Task<ScimUser>` DeleteUser(string userId);

It would be simpler to just expect a return value of Task<bool>. 

The UserService doesn't use ScimUser, it just checks for null to determine is user is not found. Also makes it easy on the application server, since I currently delete using a stored procedure, I don't want to read in the user record that is about to be deleted.

**Comment by Cephei** [comment]
The design intent is to use that ScimUser value in the future:
- logging
- firing event
- outbound provisioning
