### ISSUE TITLE
Correct way to work with Filter object

### ISSUE THREAD

**Issue by boris-meerovich-sp** [PowerDMS/Owin.Scim#48]
Hi,
I have a question according to the correct way to get filter when querying users for example.
I need to perform the filtering in the DB, thus I need a way to get the filter as a serialized object (maybe     ScimFilter class instance) and then convert it to my custom filter.
I founded just options.Filter.Filter holds the filter string.
```

  public Task<IEnumerable<ScimUser>> QueryUsers(ScimQueryOptions options) {
           
            //here I need to get a filter serialized object
            Task<IEnumerable<MyUser>> filteredUsers = _myUsersManager.FilterAsync(filter);

            return ....
        }

```

Please, advise

**Comment by Cephei** [comment]
Unfortunately, I haven't been involved in this project for quite some time. You can take a look at `https://github.com/PowerDMS/Owin.Scim/blob/master/samples/ConsoleHost/ConsoleHost/Scim/CustomUserRepository.cs#L80`

`ToPredicate<T>()` is an extension method that can convert the `ScimQueryOptions` filter to a func predicate. Unfortunately, this doesn't really help you with executing the filter in the DB. That's quite more involved and complex.

You're ideal scenario is taking a filter string passed by a query string parameter. Parsing that (which Owin.Scim does) into an expression tree. Then using a `QueryProvider` convert the expression tree into native query lang (e.g. T-SQL). This is where ORM's like `Entity Framework` are best suited. Converting an expression tree into specific SQL is **very** difficult. See: `https://msdn.microsoft.com/en-us/library/bb546158.aspx`

You may have luck by using some of the code found in `https://github.com/PowerDMS/Owin.Scim/blob/master/source/Owin.Scim/Extensions/PathFilterExpressionExtensions.cs`. This can get you your expression tree `Expression`. If you're already using EF, perhaps you can implement your own `IQueryProvider` `https://msdn.microsoft.com/en-us/library/bb546158.aspx`.

Best of luck!!!

**Comment by boris-meerovich-sp** [comment]
@Cephei Thanks for the answer!!!

**Comment by Cephei** [comment]
Just came across this old blog post. Perhaps other's have solved this or the EF team. https://nejcskofic.github.io/2017/03/20/dynamic-query-expressions-with-entity-framework/

**Comment by boris-meerovich-sp** [comment]
In my case it's nHibernate, but the idea is the same :)
Thanks
P.S.
You've built a really great project!!!
